### ISSUE TITLE
website down?

### ISSUE THREAD

**Issue by mjhoy** [mitchellwrosen/dohaskell#5]
doesn't seem to be working for me.

i had a note for myself from 2015 to check out this site, can't remember where from or why :)

**Comment by mitchellwrosen** [comment]
It is down! Sorry about that. In the meantime check out [HaskAnything](https://github.com/beerendlauwers/HaskAnything) by @beerendlauwers. They have a dump of the old dohaskell content, but I'm not sure if it's been integrated into the site yet.

**Comment by mjhoy** [comment]
cool, thanks!

**Comment by beerendlauwers** [comment]
Hi @mjhoy, we're working on importing this data set, see issue https://github.com/beerendlauwers/HaskAnything/issues/33.

@duplode has already provided some awesome scripts to transform the data into the HaskAnything format (which is essentially the Hakyll/Jekyll format). 

I haven't managed to get around to doing the actual import, and there's around 1/8th of the data set left over that are not yet mapped to the HaskAnything format (see https://github.com/duplode/dohaskell-to-haskanything-wip/blob/master/sample-output/leftovers.yaml). We'll want to decide how to map WikiBooks and textbooks to trim down that file enough that we can go through it by hand.
